# https://www.refme.com/blog/2015/11/05/haskell-travis-heroku-and-docker-oh-my/

language: sh

services:
  - docker

sudo: required

env:
  global:
    - CABALVER=1.22
    - GHCVER=7.10.2
    - ALEXVER=3.1.4
    - HAPPYVER=1.19.5

cache:
  directories:
    - '.cabal-sandbox'

before_install:
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
  - travis_retry sudo apt-get install alex-$ALEXVER
  - export PATH=/opt/alex/$ALEXVER/bin:$PATH
  - travis_retry sudo apt-get install happy-$HAPPYVER
  - export PATH=/opt/happy/$HAPPYVER/bin:$PATH
  - cabal update

install:
  - cabal sandbox init
  - cabal install --only-dependencies --enable-tests
  - cabal configure --enable-tests
  - cabal build

script:
  - cabal test
