# https://www.refme.com/blog/2015/11/05/haskell-travis-heroku-and-docker-oh-my/

language: sh

services:
  - docker

matrix:
  include:
    - os: linux
      env:
        - ALEXVER=3.1.4
        - CABALVER=1.22
        - GHCVER=7.10.2
        - HAPPYVER=1.19.5
    - os: osx

sudo: required

cache:
  directories:
    - '.cabal-sandbox'

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./scripts/before-install-linux.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/alex/$ALEXVER/bin:/opt/happy/$HAPPYVER/bin:$PATH; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ];   then ./scripts/before-install-osx.sh; fi

install:
  - cabal sandbox init
  - ./setup.sh

script:
  - cabal test
