# Temporarily disabled docker
# https://www.refme.com/blog/2015/11/05/haskell-travis-heroku-and-docker-oh-my/

dist:     trusty
language: sh
sudo:     false

matrix:
  include:
    - os: linux
      env:
        - ALEXVER=3.1.4
        - CABALVER=1.22
        - GHCVER=7.10.2
        - HAPPYVER=1.19.5
    - os: osx

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - cabal-install-$CABALVER
      - ghc-$GHCVER
      - alex-$ALEXVER
      - happy-$HAPPYVER
      - ocaml
      - camlp5
      - nodejs

cache:
  directories:
    - $HOME/.cabal
    - $HOME/.ghc
    - coq-8.5pl1
    - web/js/peacoq-ts/typings
    - web/node_modules

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./scripts/before-install-linux.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ];   then ./scripts/before-install-osx.sh; fi

install:
  - export PATH=$HOME/coq-8.5pl1/bin:$PATH
  - ./setup.sh

script:
  - cabal test
