# https://www.refme.com/blog/2015/11/05/haskell-travis-heroku-and-docker-oh-my/

language: sh

services:
  - docker

os:
  - linux
  - osx

sudo: required

env:
  global:

cache:
  directories:
    - '.cabal-sandbox'

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./scripts/before-install-linux.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/alex/$ALEXVER/bin:/opt/happy/$HAPPYVER/bin:$PATH; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ];   then ./scripts/before-install-osx.sh; fi

install:
  - cabal sandbox init
  - ./setup.sh

script:
  - cabal test
