# https://www.refme.com/blog/2015/11/05/haskell-travis-heroku-and-docker-oh-my/

language: sh

services:
  - docker

os:
  - linux
  - osx

sudo: required

env:
  global:
    - CABALVER=1.22
    - GHCVER=7.10.2
    - ALEXVER=3.1.4
    - HAPPYVER=1.19.5

cache:
  directories:
    - '.cabal-sandbox'

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./scripts/before-install-linux.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./scripts/before-install-osx.sh; fi
  - cabal update

install:
  - cabal sandbox init
  - ./setup.sh

script:
  - cabal test
