# Temporarily disabled docker
# https://www.refme.com/blog/2015/11/05/haskell-travis-heroku-and-docker-oh-my/

dist:     trusty
language: sh
sudo:     false

matrix:
  include:
    - os: linux
    - os: osx

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - cabal-install-1.24
      - ghc-head
      - alex
      - happy
      - ocaml
      - camlp5
      - nodejs

cache:
  directories:
    - $HOME/.cabal
    - $HOME/.ghc
    - coq-8.5pl1
    - web/js/peacoq-ts/typings
    - web/node_modules

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./scripts/before-install-linux.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ];   then ./scripts/before-install-osx.sh; fi

install:
  - export PATH=/opt/cabal/1.24/bin:$PATH
  - export PATH=$HOME/coq-8.5pl1/bin:$PATH
  - which coqc
  - ls $HOME
  - ls $HOME/coq-8.5pl1
  - ls $HOME/coq-8.5pl1/bin
  - ./setup.sh

script:
  - cabal test
